services:
  - type: web
    name: cobalt-api
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: API_URL
        value: https://cobalt-api.onrender.com
      - key: CORS_WILDCARD
        value: "1"
      - key: API_AUTH_REQUIRED
        value: "0"
      - key: RATELIMIT_MAX
        value: "30"
      - key: DURATION_LIMIT
        value: "10800"
